-- sql/create_tables.sql
-- TOOTHCARE Supabase Database Schema
-- Run this in your Supabase SQL editor (Dashboard → SQL → New query)
--
-- NOTES:
--  • All primary keys are UUIDs generated by gen_random_uuid()
--  • Timestamps are stored in UTC with timezone
--  • auth_uid in doctors links to auth.users.id (Supabase Auth)
--  • RLS (Row Level Security) stubs are provided at the bottom — customize per your team's policy

-- ─────────────────────────────────────────────────────────────────
-- EXTENSION
-- ─────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- for gen_random_uuid() on older Postgres

-- ─────────────────────────────────────────────────────────────────
-- TABLE: doctors
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS doctors (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_uid        UUID UNIQUE NOT NULL,                    -- links to auth.users.id
  name            TEXT NOT NULL,
  email           TEXT NOT NULL UNIQUE,
  specialization  TEXT,
  bio             TEXT,
  avatar_url      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for quick lookup by auth_uid (used in doctor-check.js)
CREATE INDEX IF NOT EXISTS idx_doctors_auth_uid ON doctors(auth_uid);

-- ─────────────────────────────────────────────────────────────────
-- TABLE: patients
-- Populated automatically on first booking via patient_id = auth.uid
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS patients (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_uid        UUID UNIQUE NOT NULL,                    -- links to auth.users.id
  name            TEXT,
  email           TEXT NOT NULL UNIQUE,
  phone           TEXT,
  date_of_birth   DATE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_patients_auth_uid ON patients(auth_uid);

-- ─────────────────────────────────────────────────────────────────
-- TABLE: services
-- Dental services offered (e.g. Implants, Whitening, Cleaning)
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS services (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name            TEXT NOT NULL UNIQUE,
  description     TEXT,
  duration_mins   INTEGER NOT NULL DEFAULT 30,             -- used to determine slot length
  price_usd       NUMERIC(10,2),
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────
-- TABLE: availability
-- Doctor's recurring weekly schedule
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS availability (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  doctor_id       UUID NOT NULL REFERENCES doctors(id) ON DELETE CASCADE,
  day_of_week     TEXT NOT NULL CHECK (
                    day_of_week IN (
                      'Monday','Tuesday','Wednesday','Thursday',
                      'Friday','Saturday','Sunday'
                    )
                  ),
  start_time      TIME NOT NULL,                           -- e.g. 09:00
  end_time        TIME NOT NULL,                           -- e.g. 17:00
  is_available    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_time_order CHECK (start_time < end_time)
);

CREATE INDEX IF NOT EXISTS idx_availability_doctor ON availability(doctor_id, day_of_week);

-- ─────────────────────────────────────────────────────────────────
-- TABLE: appointments
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS appointments (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id      UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  doctor_id       UUID NOT NULL REFERENCES doctors(id) ON DELETE RESTRICT,
  service_id      UUID NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
  appointment_ts  TIMESTAMPTZ NOT NULL,
  status          TEXT NOT NULL DEFAULT 'confirmed'
                    CHECK (status IN ('confirmed', 'cancelled', 'completed', 'no_show')),
  notes           TEXT,                                    -- optional doctor/patient notes
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Prevent double-booking: same doctor cannot have two appointments within 1 second
  CONSTRAINT uq_doctor_timeslot UNIQUE (doctor_id, appointment_ts)
);

CREATE INDEX IF NOT EXISTS idx_appointments_patient  ON appointments(patient_id, appointment_ts);
CREATE INDEX IF NOT EXISTS idx_appointments_doctor   ON appointments(doctor_id, appointment_ts);

-- ─────────────────────────────────────────────────────────────────
-- SEED DATA (optional — remove in production)
-- ─────────────────────────────────────────────────────────────────
INSERT INTO services (name, description, duration_mins, price_usd) VALUES
  ('Dental Implants',      'Permanent titanium root replacement with porcelain crown',               60, 3000.00),
  ('Teeth Whitening',      'Professional in-office laser whitening',                                  45,  299.00),
  ('General Checkup',      'Comprehensive exam, X-rays, and cleaning',                               30,  199.00),
  ('Invisalign',           'Clear aligner orthodontic treatment',                                     30, 3500.00),
  ('Root Canal',           'Endodontic therapy to save infected teeth',                               90,  700.00),
  ('Emergency Dental',     'Immediate care for dental emergencies',                                   30,  150.00)
ON CONFLICT (name) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY (RLS) — RECOMMENDED POLICIES
-- Enable RLS on all tables and define access rules.
-- Uncomment and customize before deploying to production.
-- ─────────────────────────────────────────────────────────────────

-- ALTER TABLE doctors      ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE patients     ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE services     ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE availability ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

-- ── doctors: doctors can read/update their own row; admins manage all ──────
-- CREATE POLICY "Doctors: read own record"
--   ON doctors FOR SELECT
--   USING (auth.uid() = auth_uid);

-- CREATE POLICY "Doctors: update own record"
--   ON doctors FOR UPDATE
--   USING (auth.uid() = auth_uid);

-- ── patients: patients can read/update their own row ───────────────────────
-- CREATE POLICY "Patients: read own record"
--   ON patients FOR SELECT
--   USING (auth.uid() = auth_uid);

-- CREATE POLICY "Patients: update own record"
--   ON patients FOR UPDATE
--   USING (auth.uid() = auth_uid);

-- ── services: public read; only service role can write ────────────────────
-- CREATE POLICY "Services: public read"
--   ON services FOR SELECT
--   USING (is_active = TRUE);

-- ── availability: public read; doctor can manage their own ───────────────
-- CREATE POLICY "Availability: public read"
--   ON availability FOR SELECT
--   USING (is_available = TRUE);

-- CREATE POLICY "Availability: doctor manage own"
--   ON availability FOR ALL
--   USING (
--     doctor_id IN (SELECT id FROM doctors WHERE auth_uid = auth.uid())
--   );

-- ── appointments: patient sees own; doctor sees their own appointments ────
-- CREATE POLICY "Appointments: patient read own"
--   ON appointments FOR SELECT
--   USING (
--     patient_id IN (SELECT id FROM patients WHERE auth_uid = auth.uid())
--   );

-- CREATE POLICY "Appointments: doctor read own"
--   ON appointments FOR SELECT
--   USING (
--     doctor_id IN (SELECT id FROM doctors WHERE auth_uid = auth.uid())
--   );

-- CREATE POLICY "Appointments: patient insert own"
--   ON appointments FOR INSERT
--   WITH CHECK (
--     patient_id IN (SELECT id FROM patients WHERE auth_uid = auth.uid())
--   );
